### ISSUE TITLE
Model changed to CVAE

### ISSUE THREAD

**Issue by WYan123** [ZackHodari/discrete_intonation#3]
Hello，ZackHodari ，If I add a label to the model, it becomes CVAE. Hope you can give me some inspiration.
Just modify the codec of F0_phrase_VAMP？I'm still studying related theories

**Comment by WYan123** [comment]
The encoder input is originally three-dimensional？

**Comment by ZackHodari** [comment]
The model is already a conditional VAE, I'm not sure if I understand what you're asking. What do you mean by codec in this context?

The input would be `batch_size x time_steps x feature_dimension`

**Comment by ZackHodari** [comment]
The model is already a conditional VAE, I'm not sure if I understand what you're asking. What do you mean by codec in this context?

The input would be `batch_size x time_steps x feature_dimension`

**Comment by WYan123** [comment]
Thank you very much for your reply, you mean that pseudo-input is used as an input other than features, and the model is already CVAE.
In order to generate a specific voice, I want to add another label y to the input of the model (such as sad and happy labels), but when the label is added, the code has not been successful, so please give me some guidance, and I will continue Learn.
![image](https://user-images.githubusercontent.com/51775884/105044400-a4707500-5aa1-11eb-9de3-8cd60d409490.png)

**Comment by ZackHodari** [comment]
The pseudo inputs represent the prior, they are [used to define the loss](https://github.com/ZackHodari/discrete_intonation/blob/master/vamp.py#L67). They are referred to as pseudo inputs as they are defined in input space, but they are parameters learnt by the model.

The model is a conditional VAE as it uses more than just the latent to reconstruct the input in the decoder (i.e. it uses [phone identity](https://github.com/ZackHodari/discrete_intonation/blob/master/f0_phrase_VAMP.py#L140) and [counter](https://github.com/ZackHodari/discrete_intonation/blob/master/f0_phrase_VAMP.py#L141) features).

If you want to add additional conditioning then you'll need to prep the data to work with [NumpyBinarySource](https://github.com/ZackHodari/tts_data_tools/blob/master/tts_data_tools/data_sources.py#L345) and add the inputs to the model. However, getting the model to train successfully might not be so simple, the VAMP prior can be hard to get stable. I won't be able to help you with that.

---

On a side note, if you want to control interpretable categories, take a look at [VAMPPriorDataVAE](https://github.com/ZackHodari/discrete_intonation/blob/master/vamp.py#L109). This uses certain data points as the pseudo inputs instead of having the model learn them. This is not covered in my paper or my models, but if you read through the "VAE with a VAMP" paper it discusses this idea a bit.
